package skill

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestParse_ValidMinimal(t *testing.T) {
	yaml := `
name: hello
steps:
  - id: greet
    tool: gmail_send
    args:
      to: alice@example.com
`
	s, err := Parse([]byte(yaml))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if s.Name != "hello" {
		t.Errorf("name = %q, want %q", s.Name, "hello")
	}
	if len(s.Steps) != 1 {
		t.Fatalf("steps = %d, want 1", len(s.Steps))
	}
	if s.Steps[0].ID != "greet" {
		t.Errorf("step id = %q, want %q", s.Steps[0].ID, "greet")
	}
	if s.Steps[0].Tool != "gmail_send" {
		t.Errorf("step tool = %q, want %q", s.Steps[0].Tool, "gmail_send")
	}
	if s.Steps[0].OnFail != "abort" {
		t.Errorf("on_fail = %q, want %q (default)", s.Steps[0].OnFail, "abort")
	}
}

func TestParse_ValidFull(t *testing.T) {
	yaml := `
name: full-skill
version: "1.2.0"
description: A complete skill
inputs:
  - name: recipient
    type: string
    required: true
    description: Who to send to
  - name: count
    type: int
    required: false
    default: "5"
steps:
  - id: fetch
    tool: gmail_list
    args:
      query: "is:unread"
    store: emails
    on_fail: skip
  - id: send
    tool: gmail_send
    args:
      to: "{{.input.recipient}}"
output: "{{.steps.emails}}"
meta:
  author: test
`
	s, err := Parse([]byte(yaml))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if s.Name != "full-skill" {
		t.Errorf("name = %q", s.Name)
	}
	if s.Version != "1.2.0" {
		t.Errorf("version = %q", s.Version)
	}
	if s.Description != "A complete skill" {
		t.Errorf("description = %q", s.Description)
	}
	if len(s.Inputs) != 2 {
		t.Fatalf("inputs = %d, want 2", len(s.Inputs))
	}
	if s.Inputs[0].Name != "recipient" {
		t.Errorf("input[0].name = %q", s.Inputs[0].Name)
	}
	if !s.Inputs[0].Required {
		t.Error("input[0].required = false, want true")
	}
	if s.Inputs[1].Default != "5" {
		t.Errorf("input[1].default = %q, want %q", s.Inputs[1].Default, "5")
	}
	if len(s.Steps) != 2 {
		t.Fatalf("steps = %d, want 2", len(s.Steps))
	}
	if s.Steps[0].Store != "emails" {
		t.Errorf("step[0].store = %q, want %q", s.Steps[0].Store, "emails")
	}
	if s.Steps[0].OnFail != "skip" {
		t.Errorf("step[0].on_fail = %q, want %q", s.Steps[0].OnFail, "skip")
	}
	if s.Steps[1].OnFail != "abort" {
		t.Errorf("step[1].on_fail = %q, want %q (default)", s.Steps[1].OnFail, "abort")
	}
	if s.Output != "{{.steps.emails}}" {
		t.Errorf("output = %q", s.Output)
	}
	if s.Meta["author"] != "test" {
		t.Errorf("meta[author] = %q", s.Meta["author"])
	}
}

func TestParse_MissingName(t *testing.T) {
	yaml := `
steps:
  - id: s1
    tool: gmail_list
`
	_, err := Parse([]byte(yaml))
	if err == nil {
		t.Fatal("expected error for missing name")
	}
	if !strings.Contains(err.Error(), "name is required") {
		t.Errorf("error = %q, want substring %q", err, "name is required")
	}
}

func TestParse_EmptySteps(t *testing.T) {
	yaml := `
name: no-steps
steps: []
`
	_, err := Parse([]byte(yaml))
	if err == nil {
		t.Fatal("expected error for empty steps")
	}
	if !strings.Contains(err.Error(), "at least one step") {
		t.Errorf("error = %q, want substring %q", err, "at least one step")
	}
}

func TestParse_MissingSteps(t *testing.T) {
	yaml := `
name: no-steps
`
	_, err := Parse([]byte(yaml))
	if err == nil {
		t.Fatal("expected error for missing steps")
	}
	if !strings.Contains(err.Error(), "at least one step") {
		t.Errorf("error = %q, want substring %q", err, "at least one step")
	}
}

func TestParse_MissingTool(t *testing.T) {
	yaml := `
name: bad-step
steps:
  - id: s1
`
	_, err := Parse([]byte(yaml))
	if err == nil {
		t.Fatal("expected error for missing tool")
	}
	if !strings.Contains(err.Error(), "tool is required") {
		t.Errorf("error = %q, want substring %q", err, "tool is required")
	}
}

func TestParse_DuplicateStepID(t *testing.T) {
	yaml := `
name: dup-ids
steps:
  - id: fetch
    tool: gmail_list
  - id: fetch
    tool: gmail_send
`
	_, err := Parse([]byte(yaml))
	if err == nil {
		t.Fatal("expected error for duplicate step id")
	}
	if !strings.Contains(err.Error(), "duplicate step id") {
		t.Errorf("error = %q, want substring %q", err, "duplicate step id")
	}
}

func TestParse_AutoGeneratedStepID(t *testing.T) {
	yaml := `
name: auto-id
steps:
  - tool: gmail_list
  - tool: gmail_send
`
	s, err := Parse([]byte(yaml))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if s.Steps[0].ID != "step_1" {
		t.Errorf("step[0].id = %q, want %q", s.Steps[0].ID, "step_1")
	}
	if s.Steps[1].ID != "step_2" {
		t.Errorf("step[1].id = %q, want %q", s.Steps[1].ID, "step_2")
	}
}

func TestParse_InvalidYAML(t *testing.T) {
	data := []byte(":\n\t\t- bad: {{{")
	_, err := Parse(data)
	if err == nil {
		t.Fatal("expected error for invalid YAML")
	}
	if !strings.Contains(err.Error(), "parse skill YAML") {
		t.Errorf("error = %q, want substring %q", err, "parse skill YAML")
	}
}

func TestParse_UnsupportedInputType(t *testing.T) {
	yaml := `
name: bad-type
inputs:
  - name: x
    type: float
steps:
  - id: s1
    tool: test
`
	_, err := Parse([]byte(yaml))
	if err == nil {
		t.Fatal("expected error for unsupported input type")
	}
	if !strings.Contains(err.Error(), "unsupported type") {
		t.Errorf("error = %q, want substring %q", err, "unsupported type")
	}
}

func TestParse_EmptyInputType(t *testing.T) {
	// Empty type should be accepted (defaults to unspecified/string).
	yaml := `
name: empty-type
inputs:
  - name: x
steps:
  - id: s1
    tool: test
`
	s, err := Parse([]byte(yaml))
	if err != nil {
		t.Fatalf("unexpected error for empty input type: %v", err)
	}
	if s.Inputs[0].Type != "" {
		t.Errorf("type = %q, want empty", s.Inputs[0].Type)
	}
}

func TestParse_InputWithoutName(t *testing.T) {
	yaml := `
name: nameless-input
inputs:
  - type: string
    required: true
steps:
  - id: s1
    tool: test
`
	_, err := Parse([]byte(yaml))
	if err == nil {
		t.Fatal("expected error for input without name")
	}
	if !strings.Contains(err.Error(), "input name is required") {
		t.Errorf("error = %q, want substring %q", err, "input name is required")
	}
}

func TestParse_ValidInputTypes(t *testing.T) {
	for _, typ := range []string{"string", "int", "bool"} {
		yaml := `
name: type-test
inputs:
  - name: v
    type: ` + typ + `
steps:
  - id: s1
    tool: test
`
		_, err := Parse([]byte(yaml))
		if err != nil {
			t.Errorf("type %q: unexpected error: %v", typ, err)
		}
	}
}

func TestParseFile_Success(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "test.yaml")
	content := `
name: from-file
steps:
  - id: s1
    tool: gmail_list
`
	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}
	s, err := ParseFile(path)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if s.Name != "from-file" {
		t.Errorf("name = %q, want %q", s.Name, "from-file")
	}
}

func TestParseFile_NotFound(t *testing.T) {
	_, err := ParseFile("/nonexistent/file.yaml")
	if err == nil {
		t.Fatal("expected error for missing file")
	}
	if !strings.Contains(err.Error(), "read skill file") {
		t.Errorf("error = %q, want substring %q", err, "read skill file")
	}
}

func TestParseFile_InvalidContent(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "bad.yaml")
	if err := os.WriteFile(path, []byte("name: oops\n"), 0644); err != nil {
		t.Fatal(err)
	}
	_, err := ParseFile(path)
	if err == nil {
		t.Fatal("expected error for missing steps")
	}
}
